apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  version: 7.6.2
  count: 1
  elasticsearchRefs:        
  - clusterName: elasticsearch
    name: elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: logstash-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  config: 
    pipeline.workers: 4
    log.level: debug